[target.armv7-unknown-linux-gnueabihf]
linker = "armv7-unknown-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-gnueabihf.env]
CFLAGS_armv7_unknown_linux_gnueabihf = "-O3 -ffunction-sections -fdata-sections -fPIC -Wall -Wextra -ftls-model=initial-exec -DMI_DEBUG=0"
CC_armv7_unknown_linux_gnueabihf = "armv7-unknown-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu.env]
CFLAGS_aarch64_unknown_linux_gnu = "-O3 -ffunction-sections -fdata-sections -fPIC -Wall -Wextra -ftls-model=initial-exec -DMI_DEBUG=0"
CC_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-gcc"
